language: node_js
node_js: node
cache: yarn

install:
  - yarn install

script:
  - yarn test
  - yarn run build

deploy:
  provider: firebase  
  token:
    secure: ••••••••••••••••     
  skip-cleaning: true
  local_dir: build
  on:
    branch: master