language: node_js
node_js: node
cache: yarn

install:
  - yarn install

script:
  - yarn test
  - yarn run build

deploy:
  provider: firebase  
  token: $FIREBASE_TOKEN   
  skip-cleanup: true
  on:
    branch: dev