language: node_js
node_js: 
  - "stable"
cache: 
  directories:
  - node_modules
install:
  - npm install

script:
  - yarn test
  - yarn run build

deploy:
  provider: firebase  
  token: $FIREBASE_TOKEN   
  skip-cleanup: false
  local_dir: build
  on:
    branch: dev