language: node_js
node_js: lts/*
cache:
  directories:
    - node_modules
install:
  - yarn install
script:
  - yarn run build
  - yarn test
deploy:
  provider: firebase
  token: $FIREBASE_TOKEN
  skip-cleanup: true
  local_dir: build
  on:
    branch: dev
